# -*- coding: utf-8 -*-
"""lvadsusr106_Sabarish_Lab1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153AlMsiQEZngmNlbI6Yi2ThvUvQmA-sx
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

expenses = pd.read_csv('/content/expenses.csv')
expense_df = pd.DataFrame(expenses)

#checking null values
expense_df.isnull().sum()

#checking duplicates and dropping duplicates
expense_df.duplicated().sum()
expense_df.drop_duplicates()

#visualize outliers
sns.boxplot(expense_df['charges'])
plt.show()

#checking outliers and removing outliers for charges column
q1 = expense_df['charges'].quantile(0.25)
q3 = expense_df['charges'].quantile(0.75)
IQR = q3 - q1

l_limit = q1 - (1.5*IQR)
u_limit = q3 + (1.5*IQR)
cleaned_exp_df = expense_df[~((expense_df['charges'] < l_limit) | (expense_df['charges'] > u_limit))]
print(cleaned_exp_df)

#encode categorical to numerical
lbl = LabelEncoder()
exp_df = cleaned_exp_df.copy()
exp_df['sex'] = lbl.fit_transform(exp_df['sex'])
exp_df['smoker'] = lbl.fit_transform(exp_df['smoker'])
exp_df['region'] = lbl.fit_transform(exp_df['region'])
#print(exp_df)

#model training and evalution
X = exp_df[['age', 'sex', 'bmi', 'children', 'region', 'smoker']]
y = exp_df['charges']

model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .3, random_state=42)

model = model.fit(X_train, y_train)
pred = model.predict(X_test)

mse = mean_squared_error(y_test, pred)
rms = np.sqrt(mse)
print('MSE :',mse)
print('RMS :',rms)