# -*- coding: utf-8 -*-
"""Python_Internal_Assessement_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EnjJemj6LkcbsSgymtw505ntsNA4gcAS

LAB 1

1.
"""

length = float(input('Enter length of a rectangle :'))
width = float(input('Enter width of a rectangle :'))
area = length * width
print(f'Area of Rectangle : {area}')

"""2."""

weight = float(input('Enter weight in kgs :'))
height = float(input('Enter height in m :'))
bmi = weight / (height) ** 2
print(f'BMI is {bmi}')

"""3."""

student = {}
while 1:
  name = input('Enter name (type end to close):')
  if name.lower()=='end':
    break
  score = float(input('Enter Score :'))
  student[name] = score
print(student)

"""LAB 2

1.
"""

age = int(input('Enter age :'))
if age < 18:
  print('You are a Minor')
elif age>18 and age<50:
  print('You are an Adult')
else:
  print('You are a Senior')

"""2."""

for i in range(1,50):
  if i % 2 == 0:
    print(i,end=' ')

"""3."""

password = 'Sabarish01'
while 1:
  pass_word = input('Enter Password :')
  if pass_word == password:
    print('Password Matched !')
    break

"""LAB 3

1.
"""

def avg(lst):
  len_lst = len(lst)
  sum = 0
  for i in lst:
    sum+=i
  avg = sum / len_lst
  print(f'Average of the list : {avg}')

lst = [1,4,5,6,1,5,7,4,6]
avg(lst)

"""2."""

def vowels(str):
  count = 0
  vowels = ['a','e','i','o','u']
  for i in str:
    if i.lower() in vowels:
      count+=1
  print(f'Vowels in {str} : {count}')
vowels('AEIOU')
vowels('aeiou')

"""3."""

import datetime

date_time = datetime.datetime.now()
print(date_time)

"""LAB 4

1.
"""

try:
  num_1 = int(input('Enter Num_1 :'))
  num_2 = int(input('Enter Num_2 :'))
  print(f'Result : {num_1+num_2}')
except:
  print('Enter only Integers !')

"""2."""

try:
  var_1 = int(input('Enter an integer :'))
  print('You have enetered correctly')
except ValueError:
  print('You have entered a non-integer value')

"""3."""

def div(num1,num2):
    try:
       res = num1/num2
       return res
    except ZeroDivisionError:
      print("Denominator cannot be 0.")
div(4,0)

"""LAB 5

1.
"""

text_file = open('/content/sample_data/sabarish.txt','w')
text_file.writelines("How are you ?")

"""2."""

var_1 = open('/content/sample_data/sabarish.txt','r')
print(var_1.read())

"""3."""

text_file = open('/content/sample_data/sabarish.txt','w')
text_file.writelines("Iam Fine")

var_1 = open('/content/sample_data/sabarish.txt','r')
print(var_1.read())